backend/content-command/build.gradle
backend/content-command/src/main/java/com/jikji/contentcommand/config/KafkaProducerConfig.java
backend/content-command/src/main/java/com/jikji/contentcommand/controller/ContentCommandController.java
backend/content-command/src/main/java/com/jikji/contentcommand/domain/Content.java
backend/content-command/src/main/java/com/jikji/contentcommand/domain/ImageUrl.java
backend/content-command/src/main/java/com/jikji/contentcommand/dto/message/ContentKafkaMessage.java
backend/content-command/src/main/java/com/jikji/contentcommand/dto/request/ContentUpdateRequest.java
backend/content-command/src/main/java/com/jikji/contentcommand/exception/ContentNotFoundException.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/ContentCommandService.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/ContentCommandServiceImpl.java
backend/content-command/src/main/java/com/jikji/contentcommand/util/KafkaTopic.java
backend/content-command/src/main/java/util/KafkaTopic.java
backend/content-command/src/main/resources/application-test.yml
backend/content-command/src/test/java/com/jikji/contentcommand/controller/ContentCommandControllerTest.java
backend/content-command/src/test/java/com/jikji/contentcommand/service/ContentCommandServiceTest.java
backend/gateway-service/src/main/resources/application.yml

- - -
- Content Create/Update/Delete
- 댓글, 좋아요 활성화/비활성화
- kafka

[Feature/BE] Content의 기능을 구현한다.

---

backend/content-command/src/main/java/com/jikji/contentcommand/domain/Content.java
backend/content-command/src/main/java/com/jikji/contentcommand/dto/message/ContentKafkaMessage.java
backend/content-command/src/main/java/com/jikji/contentcommand/dto/request/ContentCreateRequest.java
backend/content-command/src/main/java/com/jikji/contentcommand/dto/request/ContentUpdateRequest.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/ContentCommandServiceImpl.java
backend/content-command/src/main/java/com/jikji/contentcommand/util/KafkaTopic.java
backend/content-command/src/main/resources/application.yml
backend/content-command/src/test/java/com/jikji/contentcommand/controller/ContentCommandControllerTest.java
backend/content-command/src/test/java/com/jikji/contentcommand/service/ContentCommandServiceTest.java
backend/content-query/build.gradle
backend/content-query/src/main/java/com/jikji/contentquery/config/KafkaConsumerConfig.java
backend/content-query/src/main/java/com/jikji/contentquery/config/MongoDBConfig.java
backend/content-query/src/main/java/com/jikji/contentquery/controller/ContentQueryController.java
backend/content-query/src/main/java/com/jikji/contentquery/domain/Bookmark.java
backend/content-query/src/main/java/com/jikji/contentquery/domain/Content.java
backend/content-query/src/main/java/com/jikji/contentquery/domain/ContentLike.java
backend/content-query/src/main/java/com/jikji/contentquery/domain/ImageUrl.java
backend/content-query/src/main/java/com/jikji/contentquery/exception/ContentNotFoundException.java
backend/content-query/src/main/java/com/jikji/contentquery/repository/ContentQueryRepository.java
backend/content-query/src/main/java/com/jikji/contentquery/service/ContentQueryService.java
backend/content-query/src/main/java/com/jikji/contentquery/service/ContentQueryServiceImpl.java
backend/content-query/src/main/java/com/jikji/contentquery/service/KafkaContentConsumer.java
backend/content-query/src/main/java/com/jikji/contentquery/util/KafkaTopic.java
backend/content-query/src/main/resources/application-test.yml
backend/content-query/src/main/resources/application.yml
backend/content-query/src/test/java/com/jikji/contentquery/controller/ContentQueryControllerTest.java
backend/content-query/src/test/java/com/jikji/contentquery/service/ContentQueryServiceTest.java
backend/gateway-service/src/main/resources/application.yml

- - -
- gateway에 서비스 route 정보 추가
- content에 hashtag 포함
- 테스트 코드 작성
- content-command, content-query 사이 kafka 추가

[Feature/BE] content에 hashtag 포함 변경

---

backend/notification-server/frontend/src/home/Home.js
backend/notification-server/frontend/src/instance/EventSource.js
backend/notification-server/frontend/src/test/Test.js
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/sse/NotificationService.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/sse/SseController.java

- - -
- eventSource 싱글톤 인스턴스 추가

feat: eventSource 싱글톤 인스턴스 추가

---

backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/jwt/controller/AccessTokenController.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/controller/UserController.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/dto/UserInfoDto.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/repository/UserRepository.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/service/UserService.java

- - -
- accessToken으로 User 정보를 가져오는 API가 없었음
- Authorization Header를 통한 accessToken을 검증하고 검증 완료 시 User정보를 전달하는 API 개발

feat : 추가 accessToken/get-user-info API

---

frontend/src/components/commentLikes/LikesLayout.js
frontend/src/components/commentLikes/LikesLayout.module.scss
frontend/src/components/commentLikes/LikesList.js
frontend/src/components/comments/Comment.js
frontend/src/components/comments/Comment.module.scss
frontend/src/components/comments/CommentList.js
frontend/src/components/comments/CommentList.module.scss
frontend/src/components/comments/Commentlayout.js
frontend/src/components/comments/Commentlayout.module.scss

댓글 컴포넌트 구현, 댓글 좋아요 구현, 댓글 좋아요 리스트 모달 창 구현
- - -

Feat : Comment Component 추가

---

backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/controller/UserController.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/repository/UserRepository.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/service/UserService.java
backend/settings.gradle

- - -
- api method post -> get 수정
- 모듈 추가
- entity pk(Integer)에 맞춰 Long -> Integer 수정

[Fix/BE] user id 조회 수정

---

backend/auth-server/build.gradle
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/KafkaProducerConfig.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/dto/UserKafkaMessage.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/service/UserService.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/util/DateUtil.java
backend/auth-server/src/main/resources/application.yml
backend/gateway-service/src/main/resources/application.yml

- - - 
캠프장님께서 저번 피드백때 말씀하신 내용 반영
- auth 서버 -> user 서버로 변경했습니다.
- kafka deserializer 변경
- 사용자 서버에서 문제가 발생하여 고침 
``` groovy
ext {
set('springCloudVersion', "2021.0.5")
}
dependencyManagement {
imports {
mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
}
}
```
build.gradle에 위 내용을 추가해야 오류가 안남

[Feature/BE] user 서버 수정, kafka 추가

---

backend/content-command/src/main/java/com/jikji/contentcommand/repository/CommentRepository.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/BookmarkCommandServiceImpl.java

- - -
- bookmark service에 하드코딩되어있던 부분 수정

[Refactor/BE] 댓글 개수 가져오도록 수정

---

backend/chat-service/src/main/java/com/example/chatservice/client/UserFeignClient.java
backend/chat-service/src/main/java/com/example/chatservice/service/ChatroomService.java
backend/chat-service/src/main/resources/application.yml
backend/gateway-service/src/main/resources/application.yml

- - -
fegin client로 user api 호출 추가

feat: 사용자 정보 조회 로직 추가

---

backend/gateway-service/src/main/resources/application.yml
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/sse/NotificationService.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/sse/SseController.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/sse/dto/SliceResponseDto.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/sse/repository/NotificationRepository.java
backend/notification-server/src/main/resources/application.yml

- [BE] Notification Server에 Eureka 의존성 추가
- add, slicing api 추가
- - -
- 의존성 추가
- add, slicing api 추가
- 임시로 notification server port : 8071으로 설정

[BE] Notification Server에 Eureka 의존성 추가 & add, slicing api 추가

---

backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/KafkaConsumerConfig.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/jwt/controller/AccessTokenController.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/kafka/dto/ChatEmail.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/kafka/dto/UserInfo.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/kafka/service/KafkaConsumer.java
backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/controller/UserController.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/dto/ChatEmail.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/dto/UserInfo.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/sse/NotificationService.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/sse/SseController.java
frontend/src/components/instance/EventSource.js

- - -
- import 설정 문제
- notification-service에서 userpk 사용으로 인한 API 개설 필요성
- import설정 완료
- get-pk api 개발

feat: 추가 user-service/accessToken/get-pk api

---

backend/follow-service/src/main/java/com/example/neo4j/controller/RelationshipController.java
backend/follow-service/src/main/java/com/example/neo4j/repository/RelationshipRepository.java
backend/follow-service/src/main/java/com/example/neo4j/service/RelationshipService.java

[BE] follow 여부 조회 기능 구현

---

backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/SgdevcampJikjiInstaCloneNotificationServerApplication.java
frontend/src/pages/notification/Notification.js
frontend/src/pages/notification/components/ItemBox/NotificationBoxMiddle.js

- - -
- Notification Server와 FE 연동
- Infinite Scroll 적용

[BE, FE] Notification Server와 FE 연동

---

backend/follow-service/build.gradle
backend/follow-service/src/main/java/com/example/neo4j/KafkaProducerConfig.java
backend/follow-service/src/main/java/com/example/neo4j/controller/RelationshipController.java
backend/follow-service/src/main/java/com/example/neo4j/dto/chat/ChatMessage.java
backend/follow-service/src/main/java/com/example/neo4j/kafka/KafkaProducer.java
backend/follow-service/src/main/resources/application.yml
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/AppConfig.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/chat/ChatMessage.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/kafka/dto/ChatEmail.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/kafka/dto/UserDto.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/kafka/dto/UserDtoList.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/kafka/dto/UserInfo.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/kafka/service/KafkaConsumer.java

- - -
- notification-service messageDto 형식 문제
- messageDto 형식 수정

fix: 수정 notification-service dto 형식

---

backend/chat-service/src/main/java/com/example/chatservice/repository/MessageLikeRepository.java
backend/content-command/build.gradle
backend/content-command/src/main/java/com/jikji/contentcommand/ContentCommandApplication.java
backend/content-command/src/main/java/com/jikji/contentcommand/client/HashtagFeignClient.java
backend/content-command/src/main/java/com/jikji/contentcommand/domain/Content.java
backend/content-command/src/main/java/com/jikji/contentcommand/dto/message/ContentSearchMessage.java
backend/content-command/src/main/java/com/jikji/contentcommand/dto/request/ContentCreateRequest.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/ContentCommandServiceImpl.java
backend/content-command/src/main/java/com/jikji/contentcommand/util/HashtagUtil.java
backend/content-command/src/main/java/com/jikji/contentcommand/util/KafkaTopic.java
backend/content-command/src/test/java/com/jikji/contentcommand/controller/ContentCommandControllerTest.java
backend/content-command/src/test/java/com/jikji/contentcommand/service/ContentCommandServiceTest.java
backend/content-command/src/test/java/com/jikji/contentcommand/util/HashtagUtilTest.java
backend/gateway-service/src/main/resources/application.yml
backend/search-service/build.gradle
backend/search-service/src/main/java/com/example/searchservice/controller/HashtagController.java
backend/search-service/src/main/java/com/example/searchservice/controller/SearchController.java
backend/search-service/src/main/java/com/example/searchservice/domain/Hashtag.java
backend/search-service/src/main/java/com/example/searchservice/dto/response/ContentSearchMessage.java
backend/search-service/src/main/java/com/example/searchservice/repository/HashtagRepository.java
backend/search-service/src/main/java/com/example/searchservice/service/ContentKafkaConsumer.java
backend/search-service/src/main/java/com/example/searchservice/service/HashtagService.java
backend/search-service/src/main/resources/application.yml

[Feature/BE] 누락 부분 추가

---

backend/content-command/src/main/java/com/jikji/contentcommand/controller/BookmarkCommandController.java
backend/content-command/src/main/java/com/jikji/contentcommand/controller/CommentCommandController.java
backend/content-command/src/main/java/com/jikji/contentcommand/controller/ContentCommandController.java
backend/content-command/src/main/java/com/jikji/contentcommand/controller/LikeCommandController.java
backend/content-command/src/main/java/com/jikji/contentcommand/dto/message/SavedContentMessage.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/comment/CommentMentionService.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/comment/CommentService.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/content/BookmarkCommandService.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/content/BookmarkCommandServiceImpl.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/content/ContentCommandService.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/content/ContentCommandServiceImpl.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/content/ContentSaver.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/content/LikeCommandService.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/content/LikeCommandServiceImpl.java
backend/content-command/src/test/java/com/jikji/contentcommand/service/BookmarkCommandServiceTest.java
backend/content-command/src/test/java/com/jikji/contentcommand/service/ContentCommandServiceTest.java
backend/content-command/src/test/java/com/jikji/contentcommand/service/LikeCommandServiceTest.java
backend/content-query/src/main/java/com/jikji/contentquery/dto/message/SavedContentMessage.java
backend/content-query/src/main/java/com/jikji/contentquery/service/KafkaContentConsumer.java

- - -
- 서비스 패키지 생성(content, comment 별로 나눔)
- 카프카 수정
- content save 트랜잭션 분리

[Feature/BE] content save 트랜잭션 분리

---

backend/content-command/src/main/java/com/jikji/contentcommand/service/content/ContentCommandService.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/content/ContentCommandServiceImpl.java
backend/content-command/src/main/java/com/jikji/contentcommand/service/content/ContentSaver.java

refactor: 카프카 전송 트랜잭션에 포함시켜 데이터 불일치 방지

---

frontend/src/components/action/loginUser.js

- - -
-accessToken을 이용한 userPk API 연결

feat: 추가 frontend /user-service/user/get-pk 연결

---

backend/chat-service/src/main/java/com/example/chatservice/domain/MessageLike.java
backend/chat-service/src/main/java/com/example/chatservice/dto/request/LikeRequest.java

feat: 누락된 파일(likeRequest, MessageLike) 추가

---

backend/search-service/src/main/java/com/example/searchservice/domain/ContentIndex.java
backend/search-service/src/main/java/com/example/searchservice/domain/UserIndex.java
backend/search-service/src/main/java/com/example/searchservice/repository/ContentRepository.java
backend/search-service/src/main/java/com/example/searchservice/repository/UserRepository.java
backend/search-service/src/main/resources/static/elastic/user-mapping.json

- - -
- loginId -> nickname 변경함

[Fix/BE] 컬럼 명 변경

---

backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/kafka/service/KafkaConsumer.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/sse/NotificationService.java
backend/notification-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_notification_server/sse/SseController.java
frontend/src/components/action/loginUser.js
frontend/src/components/action/mailAuthUser.js
frontend/src/components/instance/EventSource.js
frontend/src/pages/home/Home.js
frontend/src/pages/notification/Notification.js
frontend/src/pages/user/User.js
package-lock.json
package.json

- - -
- sse frontend와 연동
- sse를 통한 웹 알림 API 연동하여 알림 게시

feat: 추가 notification-service frontend와 연동

---

backend/auth-server/src/main/java/instagram_clone/sgdevcamp_jikji_insta_clone_auth_server/user/controller/UserController.java
backend/auth-server/src/main/resources/application.yml
frontend/src/pages/follow/Follow.js
frontend/src/pages/follow/FollowerBox.js
frontend/src/pages/follow/components/ItemBox/FollowerBoxMiddle.css
frontend/src/pages/follow/components/ItemBox/FollowerBoxMiddle.js
frontend/src/pages/notification/components/ItemBox/NotificationBoxMiddle.css
frontend/src/pages/notification/components/ItemBox/NotificationBoxMiddle.js
package-lock.json

- - -
- follow 페이지와 local storage 연동 오류 해결
- Notification 페이지 디자인 수정

[FE] follow 페이지와 local storage 연동 오류 해결 및 Notification 페이지 디자인 수정
